### ISSUE TITLE
Obtener datos actualizado de municipios de Bolivia

### ISSUE THREAD

**Issue by hugocalcad** [mauforonda/casos-municipios#1]
Hola, muy interesante los datos que tienes en este repositorio, quisiera saber como los obtuviste, que utilizaste y si se puede seguir actualizando me interesa bastante estos datos y muchas gracias por tenerlos abiertos si pudieras msotrarme como yo estaria feliz de ayudar a actualizarlo!!

**Comment by mauforonda** [comment]
Hola, gracias por el interés! Actualizo los datos cuando el gobierno actualiza [la fuente](https://datosagt2020.carto.com/builder/c1cdf57c-a007-4f3f-883a-c25ebdc50986/embed), que suele ocurrir entorno al miércoles para la semana epidemiológica anterior. El plan es seguir haciendo esto mientras el gobierno lo permita. 

El gobierno actualiza regularmente esta visualización y sus cambios suelen acompañarse de nuevas restricciones para descargar y reutilizar los datos. Es decir que cada semana debo ser un poco creativo para actualizar este repositorio. En varias ocasiones he llamado la atención de personas cercanas en el gobierno, pero la respuesta ha sido siempre [indiferencia](https://twitter.com/mauforonda/status/1256700201517092866). Por eso, prefiero no subir el código. De esta manera al menos les dificulto un poco el trabajo de ocultar información de valor público. 

Si quieres ayudar, sería interesante que cruces estos datos con otras variables (por eso incluyo el código INE) y hagas tu análisis público (y cites este repositorio para que otros puedan hacer lo mismo :smile: ). Estoy seguro que existen muchas oportunidades interesantes para hallar patrones en cómo se transmite el virus y cómo llegan a reportarse los casos oficialmente. 

PS. También publico algunas gráficas con estos datos [en twitter](https://twitter.com/search?q=from%3Amauforonda%20municipio%20filter%3Aimages&src=typed_query&f=live).

**Comment by hugocalcad** [comment]
Muchas gracias por la respuesta y si te entiendo sobre la indiferencia y la actitud de restringir el acceso a estos datos tan importantes estare atento a tus actualizacion y obviamente si hay algun analisis que se pueda realizar se mencionara tu repositorio como la fuente de los datos y nuevamente muchas gracias por la informacion.
